# Generated by Django 5.0 on 2024-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_featured_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
